# This is a basic workflow to help you get started with Actions

name: Release a new version of Desktop App


on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-macos:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: install dependencies
        run: npm install
      - name: build
        run: |
          chmod +x download-checkmate.sh
          npm run electron:build